version: "3.9"

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    command: >
      bash -lc "python -m vllm.entrypoints.openai.api_server
      --host 0.0.0.0
      --port ${VLLM_PORT}
      --model ${VLLM_MODEL}
      --download-dir /models
      ${VLLM_EXTRA_ARGS}
      ${VLLM_TP:+--tensor-parallel-size ${VLLM_TP}}"
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
    volumes:
      - ${MODELS_ROOT}:/models
      - ${HF_CACHE}:/root/.cache/huggingface
    ports:
      - "${VLLM_PORT}:${VLLM_PORT}"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    shm_size: "16g"
    restart: unless-stopped

  asr-canary:
    build:
      context: ./services/asr-canary
      dockerfile: Dockerfile
    container_name: asr-canary
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
      - MODELS_ROOT=/models
      - ASR_WORKERS=${ASR_WORKERS}
    volumes:
      - ${MODELS_ROOT}:/models
      - ${HF_CACHE}:/root/.cache/huggingface
    ports:
      - "${ASR_PORT}:6000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    shm_size: "8g"
    restart: unless-stopped

  diarizer:
    build:
      context: ./services/diarizer
      dockerfile: Dockerfile
    container_name: diarizer
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
      - MODELS_ROOT=/models
    volumes:
      - ${MODELS_ROOT}:/models
      - ${HF_CACHE}:/root/.cache/huggingface
    ports:
      - "${DIAR_PORT}:7000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    shm_size: "8g"
    restart: unless-stopped

  admin:
    build:
      context: ./services/admin
      dockerfile: Dockerfile
    container_name: admin
    environment:
      - VLLM_BASE=http://vllm:${VLLM_PORT}
      - ASR_BASE=http://asr-canary:6000
      - DIAR_BASE=http://diarizer:7000
    volumes:
      - ${MODELS_ROOT}:/models:ro
      - ${HF_CACHE}:/root/.cache/huggingface:ro
    ports:
      - "${ADMIN_PORT}:8080"
    depends_on:
      - vllm
      - asr-canary
      - diarizer
    restart: unless-stopped
